apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: sample-app
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  project: default 
  source:
    repoURL: https://github.com/landonb629/node-on-aks.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default