apiVersion: apps/v1
kind: Deployment 
metadata:
  name: demo-app 
  labels:
    tier: frontend
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: demo-app
      labels:
        tier: frontend
    spec:
      containers:
        - name: demo-app 
          image: nginx:latest