apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: node-frontend
  labels:
    tier: frontend
    env: production
spec:
  replicas: 2 
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: node-frontend
      labels:
        tier: frontend
        env: production
    spec:
      containers:
        - name: node-frontend
          image: frontend:v1.1
          imagePullPolicy: Never