apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: node-frontend
  labels:
    tier: frontend
    env: production
spec:
  replicas: 2 
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: node-frontend
      labels:
        tier: frontend
        env: production
    spec:
      containers:
        - name: node-frontend
          image: 500731508494.dkr.ecr.us-east-2.amazonaws.com/frontend:v.a15997576d2c2bf35bc69331ebc5c0810972ce8e