apiVersion: apps/v1
kind: Deployment 
metadata:
  name: service2
  labels: 
    tier: backend 
    service: service2
spec:
  replicas: 2 
  selector:
    matchLabels:
      service: service2
  template:
    metadata:
      name: service2 
      labels:
        tier: backend
        service: service2
    spec:
      containers:
        - name: service2 
          image: 500731508494.dkr.ecr.us-east-2.amazonaws.com/service2:v1.1