apiVersion: apps/v1
kind: Deployment 
metadata:
  name: service1 
  labels: 
    tier: backend 
    service: service1 
spec:
  replicas: 2 
  selector:
    matchLabels:
      service: service1
  template:
    metadata:
      name: service1 
      labels:
        tier: backend
        service: service1
    spec:
      containers:
        - name: service1 
          image: service1
          imagePullPolicy: Never
      