name: Microservice frontend CD 
on:
  pull_request:
    types: 
      - closed 
    paths: 
      - "frontend/**"
    branches:
      - "main"

jobs: 
  CD: 
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    defaults:
      run:
        working-directory: ./manifests
    steps:
      - name: checkout repo 
        uses: actions/checkout@v3
      
      - name: check the fold 
        run: | 
          echo "${{ github.event.pull_request.merged }}"
          echo "${{ github.event.pull_request }}"
          echo "${{ github.event.action }}"

      - name: update manifest 
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo "$IMAGE_TAG"
          sed -i 's/frontend:v.*/frontend:$IMAGE_TAG/g' frontend.yml
          cat frontend.yml
    
      - name: setup git configuration 
        run: | 
          git config user.name "github actions bot"
          git config user.email "<>"

      - name: commit 
        run: | 
          git add ./
          git commit -m "updating frontend manifest for deployment"
          git push origin main