name: Microservice frontend CD 
on:
  pull_request:
    types: 
      - closed 
    paths: 
      - "frontend/**"
    branches:
      - "main"

jobs: 
  CD: 
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    defaults:
      run:
        working-directory: ./manifests
    steps:
      - name: update manifest 
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sed -i 's/frontend:v.*/$IMAGE_TAG/g' frontend.yml
    
      - name: setup git configuration 
        run: | 
          git config user.name "github actions bot"
          git config user.email "<>"

      - name: commit 
        run: | 
          git add ./
          git commit -m "updating frontend manifest for deployment"
          git push origin main