name: Microservice frontend CI 
on:
  pull_request:
    types: 
      - opened
    paths: 
      - "frontend/**"
    branches:
      - "main"
  
jobs: 
  CI: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: checkout repo 
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: login to ecr 
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: echoing the base before and after
        run: | 
          echo "${{ github.event.base_ref }}"
          echo "${{ github.event.before}}"
      
      - name: build and push image 
        env: 
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPOSITORY: frontend
          IMAGE_TAG: ${{ github.sha }}
        run: | 
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG . 
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          
      
        
      
      
         
         
    