name: Microservice frontend CI 
on:
  pull_request:
    types: 
      - opened
      - closed 
    paths: 
      - "frontend/**"
    branches:
      - "main"
  
jobs: 
  CI: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: checkout repo 
        uses: actions/checkout@v3
      
      - name: login to ecr 
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: build and push image 
        env: 
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPOSITORY: service1
          IMAGE_TAG: ${{ github.sha }}
        run: | 
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG . 
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          
      - name: update manifest 
        if: ${{ github.event_path}} == 'pull_request' && ${{github.event.action}} == 'closed'
        run: |
          cd ../manifests
          sed -i 's/service1:v.*'/service`:$IMAGE_TAG/g` frontend.yml
        
      
      
         
         
    