name: Infrastructure CD pipeline
on: 
  push:
    paths:
      - "infra/**"
    branches:
      - "main"

jobs:
  CD:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    
    steps:
      - name: checkout repo 
        uses: actions/checkout@v3
      
      - name: setup terraform 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2
      
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
      
      - name: terraform init
        run: | 
          terraform init
      
      - name: terraform fmt 
        run: | 
          terraform fmt 
      
      - name: terraform apply 
        run: | 
          terraform apply -auto-approve