name: Infrastructure CI pipeline
on: 
  push:
    paths:
      - "infra/**"
    branches:
      - "!main"
      - "**"

jobs: 
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
     
    steps:
      - name: checkout repo 
        uses: actions/checkout@v3
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2
      
      - name: terraform validate 
        run: | 
          terraform validate 
      
      - name: terraform fmt
        run: | 
          terraform fmt 
      
      - name: terraform plan
        run: | 
          terrafom plan
        