name: Microservice Service 2 
on:
  pull_request:
    types: 
      - closed 
    paths: 
      - "service2/**"
    branches:
      - "main"

jobs: 
  CD: 
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    defaults:
      run:
        working-directory: ./manifests
    steps:
      - name: checkout repo 
        uses: actions/checkout@v3
 
      - name: update manifest 
        env:
          IMAGE_TAG: ${{ github.event.pull_request.head.sha }}
        run: |
          sed -i 's/service2:.*/service2:${{env.IMAGE_TAG}}/g' service2.yml
    
      - name: setup git configuration 
        run: | 
          git config user.name "github actions bot"
          git config user.email "<>"

      - name: commit 
        run: | 
          git add ./
          git commit -m "updating service1 manifest for deployment"
          git push origin main